version: 2.1
orbs:
  node: circleci/node@4.1.0
jobs:
  build:
    docker: 
      - image: "cimg/base:stable"
    steps:
      - node/install
      - checkout
      # - run: echo "Hello World, this is Udagram!"
      - run: npm run frontend:install
      - run: npm run api:install
      - run: npm run frontend:build
      - run: npm run api:build